package com.gnut3ll4.signetswebservices.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 06/09/2016
//
//---------------------------------------------------


import com.gnut3ll4.signetswebservices.model.OperationResult;

public interface IServiceEvents
{
    public void Starting();
    public void Completed(OperationResult result);
}
