package com.gnut3ll4.signetswebservices.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 06/09/2016
//
//---------------------------------------------------

import android.os.AsyncTask;
import android.util.Log;

import com.gnut3ll4.signetswebservices.model.Etudiant;
import com.gnut3ll4.signetswebservices.model.ListeCoursHoraire;
import com.gnut3ll4.signetswebservices.model.ListeDeCours;
import com.gnut3ll4.signetswebservices.model.ListeDeSessions;
import com.gnut3ll4.signetswebservices.model.ListeDesActivitesEtProf;
import com.gnut3ll4.signetswebservices.model.ListeDesCoequipiers;
import com.gnut3ll4.signetswebservices.model.ListeDesElementsEvaluation;
import com.gnut3ll4.signetswebservices.model.ListeDesProgrammes;
import com.gnut3ll4.signetswebservices.model.ListeEvaluationsCours;
import com.gnut3ll4.signetswebservices.model.ListeHoraireExamensFinaux;
import com.gnut3ll4.signetswebservices.model.ListeJoursRemplaces;
import com.gnut3ll4.signetswebservices.model.ListeSeances;

import org.ksoap2.HeaderProperty;
import org.ksoap2.SoapFault;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.transport.HttpsTransportSE;
import org.ksoap2.transport.Transport;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;


public class SignetsMobileSoap12 {
    public List<HeaderProperty> httpHeaders;
    public boolean enableLogging;
    String url = "https://signets-ens.etsmtl.ca/Secure/WebServices/SignetsMobile.asmx";
    int timeOut = 60000;
    IServiceEvents callback;

    public SignetsMobileSoap12() {
    }

    public SignetsMobileSoap12(IServiceEvents callback) {
        this.callback = callback;
    }

    public SignetsMobileSoap12(IServiceEvents callback, String url) {
        this.callback = callback;
        this.url = url;
    }

    public SignetsMobileSoap12(IServiceEvents callback, String url, int timeOut) {
        this.callback = callback;
        this.url = url;
        this.timeOut = timeOut;
    }

    protected Transport createTransport() {
        try {
            URI uri = new URI(url);
            if (uri.getScheme().equalsIgnoreCase("https")) {
                int port = uri.getPort() > 0 ? uri.getPort() : 443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            } else {
                return new HttpTransportSE(url, timeOut);
            }

        } catch (URISyntaxException e) {
        }
        return null;
    }

    protected ExtendedSoapSerializationEnvelope createEnvelope() {
        ExtendedSoapSerializationEnvelope envelope = new ExtendedSoapSerializationEnvelope(ExtendedSoapSerializationEnvelope.VER12);
        return envelope;
    }

    protected List sendRequest(String methodName, ExtendedSoapSerializationEnvelope envelope, Transport transport) throws Exception {
        return transport.call(methodName, envelope, httpHeaders);
    }

    Object getResult(Class destObj, Object source, String resultName, ExtendedSoapSerializationEnvelope __envelope) throws Exception {
        if (source == null) {
            return null;
        }
        if (source instanceof SoapPrimitive) {
            SoapPrimitive soap = (SoapPrimitive) source;
            if (soap.getName().equals(resultName)) {
                Object instance = __envelope.get(source, destObj);
                return instance;
            }
        } else {
            SoapObject soap = (SoapObject) source;
            if (soap.hasProperty(resultName)) {
                Object j = soap.getProperty(resultName);
                if (j == null) {
                    return null;
                }
                Object instance = __envelope.get(j, destObj);
                return instance;
            } else if (soap.getName().equals(resultName)) {
                Object instance = __envelope.get(source, destObj);
                return instance;
            }
        }

        return null;
    }

    public String HelloWorld() throws Exception {
        return (String) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "HelloWorld");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                SoapObject __soap = (SoapObject) __result;
                Object obj = __soap.getProperty("HelloWorldResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    return j.toString();
                } else if (obj != null && obj instanceof String) {
                    return (String) obj;
                }
                return null;
            }
        }, "http://etsmtl.ca/HelloWorld");
    }

    public AsyncTask<Void, Void, OperationResult<String>> HelloWorldAsync() {
        return executeAsync(new Functions.IFunc<String>() {
            public String Func() throws Exception {
                return HelloWorld();
            }
        });
    }

    public String echo(final String chaine) throws Exception {
        return (String) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "echo");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "chaine";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(chaine != null ? chaine : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                SoapObject __soap = (SoapObject) __result;
                Object obj = __soap.getProperty("echoResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    return j.toString();
                } else if (obj != null && obj instanceof String) {
                    return (String) obj;
                }
                return null;
            }
        }, "http://etsmtl.ca/echo");
    }

    public AsyncTask<Void, Void, OperationResult<String>> echoAsync(final String chaine) {
        return executeAsync(new Functions.IFunc<String>() {
            public String Func() throws Exception {
                return echo(chaine);
            }
        });
    }

    public Etudiant infoEtudiant(final String codeAccesUniversel, final String motPasse) throws Exception {
        return (Etudiant) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "infoEtudiant");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return (Etudiant) getResult(Etudiant.class, __result, "infoEtudiantResult", __envelope);
            }
        }, "http://etsmtl.ca/infoEtudiant");
    }

    public AsyncTask<Void, Void, OperationResult<Etudiant>> infoEtudiantAsync(final String codeAccesUniversel, final String motPasse) {
        return executeAsync(new Functions.IFunc<Etudiant>() {
            public Etudiant Func() throws Exception {
                return infoEtudiant(codeAccesUniversel, motPasse);
            }
        });
    }

    public ListeDeCours listeCours(final String codeAccesUniversel, final String motPasse) throws Exception {
        return (ListeDeCours) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeCours");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return (ListeDeCours) getResult(ListeDeCours.class, __result, "listeCoursResult", __envelope);
            }
        }, "http://etsmtl.ca/listeCours");
    }

    public AsyncTask<Void, Void, OperationResult<ListeDeCours>> listeCoursAsync(final String codeAccesUniversel, final String motPasse) {
        return executeAsync(new Functions.IFunc<ListeDeCours>() {
            public ListeDeCours Func() throws Exception {
                return listeCours(codeAccesUniversel, motPasse);
            }
        });
    }

    public Boolean donneesAuthentificationValides(final String codeAccesUniversel, final String motPasse) throws Exception {
        return (Boolean) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "donneesAuthentificationValides");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                SoapObject __soap = (SoapObject) __result;
                Object obj = __soap.getProperty("donneesAuthentificationValidesResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    return new Boolean(j.toString());
                } else if (obj != null && obj instanceof Boolean) {
                    return (Boolean) obj;
                }
                return null;
            }
        }, "http://etsmtl.ca/donneesAuthentificationValides");
    }

    public AsyncTask<Void, Void, OperationResult<Boolean>> donneesAuthentificationValidesAsync(final String codeAccesUniversel, final String motPasse) {
        return executeAsync(new Functions.IFunc<Boolean>() {
            public Boolean Func() throws Exception {
                return donneesAuthentificationValides(codeAccesUniversel, motPasse);
            }
        });
    }

    public ListeDeCours listeCoursIntervalleSessions(final String codeAccesUniversel, final String motPasse, final String SesDebut, final String SesFin) throws Exception {
        return (ListeDeCours) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeCoursIntervalleSessions");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "SesDebut";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(SesDebut != null ? SesDebut : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "SesFin";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(SesFin != null ? SesFin : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return (ListeDeCours) getResult(ListeDeCours.class, __result, "listeCoursIntervalleSessionsResult", __envelope);
            }
        }, "http://etsmtl.ca/listeCoursIntervalleSessions");
    }

    public AsyncTask<Void, Void, OperationResult<ListeDeCours>> listeCoursIntervalleSessionsAsync(final String codeAccesUniversel, final String motPasse, final String SesDebut, final String SesFin) {
        return executeAsync(new Functions.IFunc<ListeDeCours>() {
            public ListeDeCours Func() throws Exception {
                return listeCoursIntervalleSessions(codeAccesUniversel, motPasse, SesDebut, SesFin);
            }
        });
    }

    public ListeDeSessions listeSessions(final String codeAccesUniversel, final String motPasse) throws Exception {
        return (ListeDeSessions) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeSessions");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return (ListeDeSessions) getResult(ListeDeSessions.class, __result, "listeSessionsResult", __envelope);
            }
        }, "http://etsmtl.ca/listeSessions");
    }

    public AsyncTask<Void, Void, OperationResult<ListeDeSessions>> listeSessionsAsync(final String codeAccesUniversel, final String motPasse) {
        return executeAsync(new Functions.IFunc<ListeDeSessions>() {
            public ListeDeSessions Func() throws Exception {
                return listeSessions(codeAccesUniversel, motPasse);
            }
        });
    }

    public ListeDesProgrammes listeProgrammes(final String codeAccesUniversel, final String motPasse) throws Exception {
        return (ListeDesProgrammes) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeProgrammes");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return (ListeDesProgrammes) getResult(ListeDesProgrammes.class, __result, "listeProgrammesResult", __envelope);
            }
        }, "http://etsmtl.ca/listeProgrammes");
    }

    public AsyncTask<Void, Void, OperationResult<ListeDesProgrammes>> listeProgrammesAsync(final String codeAccesUniversel, final String motPasse) {
        return executeAsync(new Functions.IFunc<ListeDesProgrammes>() {
            public ListeDesProgrammes Func() throws Exception {
                return listeProgrammes(codeAccesUniversel, motPasse);
            }
        });
    }

    public ListeDesCoequipiers listeCoequipiers(final String codeAccesUniversel, final String motPasse, final String pSigle, final String pGroupe, final String pSession, final String pNomElementEval) throws Exception {
        return (ListeDesCoequipiers) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeCoequipiers");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pSigle";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pSigle != null ? pSigle : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pGroupe";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pGroupe != null ? pGroupe : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pSession";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pSession != null ? pSession : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pNomElementEval";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pNomElementEval != null ? pNomElementEval : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return getResult(ListeDesCoequipiers.class, __result, "listeCoequipiersResult", __envelope);
            }
        }, "http://etsmtl.ca/listeCoequipiers");
    }

    public AsyncTask<Void, Void, OperationResult<ListeDesCoequipiers>> listeCoequipiersAsync(final String codeAccesUniversel, final String motPasse, final String pSigle, final String pGroupe, final String pSession, final String pNomElementEval) {
        return executeAsync(new Functions.IFunc<ListeDesCoequipiers>() {
            public ListeDesCoequipiers Func() throws Exception {
                return listeCoequipiers(codeAccesUniversel, motPasse, pSigle, pGroupe, pSession, pNomElementEval);
            }
        });
    }

    public ListeDesElementsEvaluation listeElementsEvaluation(final String codeAccesUniversel, final String motPasse, final String pSigle, final String pGroupe, final String pSession) throws Exception {
        return (ListeDesElementsEvaluation) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeElementsEvaluation");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pSigle";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pSigle != null ? pSigle : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pGroupe";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pGroupe != null ? pGroupe : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pSession";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pSession != null ? pSession : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return getResult(ListeDesElementsEvaluation.class, __result, "listeElementsEvaluationResult", __envelope);
            }
        }, "http://etsmtl.ca/listeElementsEvaluation");
    }

    public AsyncTask<Void, Void, OperationResult<ListeDesElementsEvaluation>> listeElementsEvaluationAsync(final String codeAccesUniversel, final String motPasse, final String pSigle, final String pGroupe, final String pSession) {
        return executeAsync(new Functions.IFunc<ListeDesElementsEvaluation>() {
            public ListeDesElementsEvaluation Func() throws Exception {
                return listeElementsEvaluation(codeAccesUniversel, motPasse, pSigle, pGroupe, pSession);
            }
        });
    }

    public ListeDesActivitesEtProf listeHoraireEtProf(final String codeAccesUniversel, final String motPasse, final String pSession) throws Exception {
        return (ListeDesActivitesEtProf) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeHoraireEtProf");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pSession";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pSession != null ? pSession : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return getResult(ListeDesActivitesEtProf.class, __result, "listeHoraireEtProfResult", __envelope);
            }
        }, "http://etsmtl.ca/listeHoraireEtProf");
    }

    public AsyncTask<Void, Void, OperationResult<ListeDesActivitesEtProf>> listeHoraireEtProfAsync(final String codeAccesUniversel, final String motPasse, final String pSession) {
        return executeAsync(new Functions.IFunc<ListeDesActivitesEtProf>() {
            public ListeDesActivitesEtProf Func() throws Exception {
                return listeHoraireEtProf(codeAccesUniversel, motPasse, pSession);
            }
        });
    }

    public ListeHoraireExamensFinaux listeHoraireExamensFin(final String codeAccesUniversel, final String motPasse, final String pSession) throws Exception {
        return (ListeHoraireExamensFinaux) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeHoraireExamensFin");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pSession";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pSession != null ? pSession : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return getResult(ListeHoraireExamensFinaux.class, __result, "listeHoraireExamensFinResult", __envelope);
            }
        }, "http://etsmtl.ca/listeHoraireExamensFin");
    }

    public AsyncTask<Void, Void, OperationResult<ListeHoraireExamensFinaux>> listeHoraireExamensFinAsync(final String codeAccesUniversel, final String motPasse, final String pSession) {
        return executeAsync(new Functions.IFunc<ListeHoraireExamensFinaux>() {
            public ListeHoraireExamensFinaux Func() throws Exception {
                return listeHoraireExamensFin(codeAccesUniversel, motPasse, pSession);
            }
        });
    }

    public ListeCoursHoraire lireHoraire(final String pSession, final String prefixeSigleCours) throws Exception {
        return (ListeCoursHoraire) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "lireHoraire");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pSession";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pSession != null ? pSession : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "prefixeSigleCours";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(prefixeSigleCours != null ? prefixeSigleCours : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return getResult(ListeCoursHoraire.class, __result, "lireHoraireResult", __envelope);
            }
        }, "http://etsmtl.ca/lireHoraire");
    }

    public AsyncTask<Void, Void, OperationResult<ListeCoursHoraire>> lireHoraireAsync(final String pSession, final String prefixeSigleCours) {
        return executeAsync(new Functions.IFunc<ListeCoursHoraire>() {
            public ListeCoursHoraire Func() throws Exception {
                return lireHoraire(pSession, prefixeSigleCours);
            }
        });
    }

    public ListeJoursRemplaces lireJoursRemplaces(final String pSession) throws Exception {
        return (ListeJoursRemplaces) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "lireJoursRemplaces");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pSession";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pSession != null ? pSession : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return getResult(ListeJoursRemplaces.class, __result, "lireJoursRemplacesResult", __envelope);
            }
        }, "http://etsmtl.ca/lireJoursRemplaces");
    }

    public AsyncTask<Void, Void, OperationResult<ListeJoursRemplaces>> lireJoursRemplacesAsync(final String pSession) {
        return executeAsync(new Functions.IFunc<ListeJoursRemplaces>() {
            public ListeJoursRemplaces Func() throws Exception {
                return lireJoursRemplaces(pSession);
            }
        });
    }

    public ListeSeances lireHoraireDesSeances(final String codeAccesUniversel, final String motPasse, final String pCoursGroupe, final String pSession, final String pDateDebut, final String pDateFin) throws Exception {
        return (ListeSeances) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "lireHoraireDesSeances");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pCoursGroupe";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pCoursGroupe != null ? pCoursGroupe : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pSession";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pSession != null ? pSession : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pDateDebut";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pDateDebut != null ? pDateDebut : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pDateFin";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pDateFin != null ? pDateFin : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return getResult(ListeSeances.class, __result, "lireHoraireDesSeancesResult", __envelope);
            }
        }, "http://etsmtl.ca/lireHoraireDesSeances");
    }

    public AsyncTask<Void, Void, OperationResult<ListeSeances>> lireHoraireDesSeancesAsync(final String codeAccesUniversel, final String motPasse, final String pCoursGroupe, final String pSession, final String pDateDebut, final String pDateFin) {
        return executeAsync(new Functions.IFunc<ListeSeances>() {
            public ListeSeances Func() throws Exception {
                return lireHoraireDesSeances(codeAccesUniversel, motPasse, pCoursGroupe, pSession, pDateDebut, pDateFin);
            }
        });
    }

    public ListeEvaluationsCours lireEvaluationCours(final String codeAccesUniversel, final String motPasse, final String pSession) throws Exception {
        return (ListeEvaluationsCours) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "lireEvaluationCours");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "codeAccesUniversel";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel != null ? codeAccesUniversel : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "motPasse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse != null ? motPasse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://etsmtl.ca/";
                __info.name = "pSession";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(pSession != null ? pSession : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception {
                return getResult(ListeEvaluationsCours.class, __result, "lireEvaluationCoursResult", __envelope);
            }
        }, "http://etsmtl.ca/lireEvaluationCours");
    }

    public AsyncTask<Void, Void, OperationResult<ListeEvaluationsCours>> lireEvaluationCoursAsync(final String codeAccesUniversel, final String motPasse, final String pSession) {
        return executeAsync(new Functions.IFunc<ListeEvaluationsCours>() {
            public ListeEvaluationsCours Func() throws Exception {
                return lireEvaluationCours(codeAccesUniversel, motPasse, pSession);
            }
        });
    }

    protected Object execute(IWcfMethod wcfMethod, String methodName) throws Exception {
        Transport __httpTransport = createTransport();
        __httpTransport.debug = enableLogging;
        ExtendedSoapSerializationEnvelope __envelope = wcfMethod.CreateSoapEnvelope();
        try {
            sendRequest(methodName, __envelope, __httpTransport);

        } finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    Log.i("requestDump", __httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    Log.i("responseDump", __httpTransport.responseDump);
                }
            }
        }
        Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof SoapFault) {
            SoapFault __fault = (SoapFault) __retObj;
            throw convertToException(__fault, __envelope);
        } else {
            return wcfMethod.ProcessResult(__envelope, __retObj);
        }
    }

    protected <T> AsyncTask<Void, Void, OperationResult<T>> executeAsync(final Functions.IFunc<T> func) {
        return new AsyncTask<Void, Void, OperationResult<T>>() {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            }

            ;

            @Override
            protected OperationResult<T> doInBackground(Void... params) {
                OperationResult<T> result = new OperationResult<T>();
                try {
                    result.Result = func.Func();
                } catch (Exception ex) {
                    ex.printStackTrace();
                    result.Exception = ex;
                }
                return result;
            }

            @Override
            protected void onPostExecute(OperationResult<T> result) {
                callback.Completed(result);
            }
        }.execute();
    }

    Exception convertToException(SoapFault fault, ExtendedSoapSerializationEnvelope envelope) {

        return new Exception(fault.faultstring);
    }

    interface IWcfMethod {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

        Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception;
    }
}


