package com.gnut3ll4.signetswebservices.model;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 06/09/2016
//
//---------------------------------------------------


import com.gnut3ll4.signetswebservices.soap.ExtendedSoapSerializationEnvelope;
import com.gnut3ll4.signetswebservices.soap.Helper;

import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class EvaluationCours extends AttributeContainer implements KvmSerializable
{

    
    public String Sigle;
    
    public String Groupe;
    
    public String Enseignant;
    
    public java.util.Date DateDebutEvaluation;
    
    public java.util.Date DateFinEvaluation;
    
    public String TypeEvaluation;
    
    public Boolean EstComplete=false;

    public EvaluationCours()
    {
    }

    public EvaluationCours(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("Sigle"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Sigle = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Sigle = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Groupe"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Groupe = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Groupe = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Enseignant"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Enseignant = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Enseignant = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("DateDebutEvaluation"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.DateDebutEvaluation = Helper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.DateDebutEvaluation = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("DateFinEvaluation"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.DateFinEvaluation = Helper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.DateFinEvaluation = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("TypeEvaluation"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.TypeEvaluation = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.TypeEvaluation = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("EstComplete"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.EstComplete = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.EstComplete = (Boolean)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Sigle!=null?this.Sigle:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Groupe!=null?this.Groupe:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Enseignant!=null?this.Enseignant:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.DateDebutEvaluation!=null? Helper.getDateTimeFormat().format(this.DateDebutEvaluation):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.DateFinEvaluation!=null? Helper.getDateTimeFormat().format(this.DateFinEvaluation):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.TypeEvaluation!=null?this.TypeEvaluation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return EstComplete;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Sigle";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Groupe";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Enseignant";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateDebutEvaluation";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateFinEvaluation";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TypeEvaluation";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "EstComplete";
            info.namespace= "http://etsmtl.ca/";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
