package com.gnut3ll4.signetswebservices.model;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 06/09/2016
//
//---------------------------------------------------


import com.gnut3ll4.signetswebservices.soap.ExtendedSoapSerializationEnvelope;

import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class Programme extends AttributeContainer implements KvmSerializable
{

    
    public String code;
    
    public String libelle;
    
    public String profil;
    
    public String statut;
    
    public String sessionDebut;
    
    public String sessionFin;
    
    public String moyenne;
    
    public String nbEquivalences;
    
    public String nbCrsReussis;
    
    public String nbCrsEchoues;
    
    public String nbCreditsInscrits;
    
    public String nbCreditsCompletes;
    
    public String nbCreditsPotentiels;
    
    public String nbCreditsRecherche;

    public Programme()
    {
    }

    public Programme(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("code"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.code = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.code = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("libelle"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.libelle = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.libelle = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("profil"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.profil = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.profil = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("statut"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.statut = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.statut = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("sessionDebut"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.sessionDebut = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.sessionDebut = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("sessionFin"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.sessionFin = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.sessionFin = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("moyenne"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.moyenne = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.moyenne = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("nbEquivalences"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.nbEquivalences = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.nbEquivalences = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("nbCrsReussis"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.nbCrsReussis = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.nbCrsReussis = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("nbCrsEchoues"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.nbCrsEchoues = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.nbCrsEchoues = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("nbCreditsInscrits"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.nbCreditsInscrits = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.nbCreditsInscrits = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("nbCreditsCompletes"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.nbCreditsCompletes = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.nbCreditsCompletes = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("nbCreditsPotentiels"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.nbCreditsPotentiels = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.nbCreditsPotentiels = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("nbCreditsRecherche"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.nbCreditsRecherche = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.nbCreditsRecherche = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.code!=null?this.code:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.libelle!=null?this.libelle:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.profil!=null?this.profil:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.statut!=null?this.statut:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.sessionDebut!=null?this.sessionDebut:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.sessionFin!=null?this.sessionFin:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.moyenne!=null?this.moyenne:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.nbEquivalences!=null?this.nbEquivalences:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.nbCrsReussis!=null?this.nbCrsReussis:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.nbCrsEchoues!=null?this.nbCrsEchoues:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.nbCreditsInscrits!=null?this.nbCreditsInscrits:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.nbCreditsCompletes!=null?this.nbCreditsCompletes:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.nbCreditsPotentiels!=null?this.nbCreditsPotentiels:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.nbCreditsRecherche!=null?this.nbCreditsRecherche:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 14;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "code";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "libelle";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "profil";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "statut";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "sessionDebut";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "sessionFin";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "moyenne";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nbEquivalences";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nbCrsReussis";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nbCrsEchoues";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nbCreditsInscrits";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nbCreditsCompletes";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nbCreditsPotentiels";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nbCreditsRecherche";
            info.namespace= "http://etsmtl.ca/";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
