package com.gnut3ll4.signetswebservices.model;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 06/09/2016
//
//---------------------------------------------------




import com.gnut3ll4.signetswebservices.soap.IServiceEvents;

import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;

import java.util.List;


public class SignetsMobileSoap12
{
    interface TEQIWcfMethod
    {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object result) throws java.lang.Exception;
    }

    String url="https://signets-ens.etsmtl.ca/Secure/WebServices/SignetsMobile.asmx";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    IServiceEvents callback;
    public SignetsMobileSoap12(){}

    public SignetsMobileSoap12(IServiceEvents callback)
    {
        this.callback = callback;
    }
    public SignetsMobileSoap12(IServiceEvents callback, String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public SignetsMobileSoap12(IServiceEvents callback, String url, int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected ExtendedSoapSerializationEnvelope createEnvelope()
    {
        ExtendedSoapSerializationEnvelope envelope= new ExtendedSoapSerializationEnvelope(ExtendedSoapSerializationEnvelope.VER12);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName, ExtendedSoapSerializationEnvelope envelope, org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,ExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public String HelloWorld( ) throws java.lang.Exception
    {
        return (String)execute(new TEQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "HelloWorld");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("HelloWorldResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://etsmtl.ca/HelloWorld");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> HelloWorldAsync()
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return HelloWorld( );
            }
        });
    }
    
    public String echo(final String chaine ) throws java.lang.Exception
    {
        return (String)execute(new TEQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "echo");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="chaine";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(chaine!=null?chaine:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("echoResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://etsmtl.ca/echo");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> echoAsync(final String chaine)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return echo( chaine);
            }
        });
    }
    
    public Etudiant infoEtudiant(final String codeAccesUniversel, final String motPasse ) throws java.lang.Exception
    {
        return (Etudiant)execute(new TEQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "infoEtudiant");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="codeAccesUniversel";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel!=null?codeAccesUniversel:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="motPasse";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse!=null?motPasse:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                return (Etudiant)getResult(Etudiant.class,__result,"infoEtudiantResult",__envelope);
            }
        },"http://etsmtl.ca/infoEtudiant");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult<Etudiant>> infoEtudiantAsync(final String codeAccesUniversel, final String motPasse)
    {
        return executeAsync(new Functions.IFunc<Etudiant>() {
            public Etudiant Func() throws java.lang.Exception {
                return infoEtudiant( codeAccesUniversel,motPasse);
            }
        });
    }
    
    public ListeDeCours listeCours(final String codeAccesUniversel, final String motPasse ) throws java.lang.Exception
    {
        return (ListeDeCours)execute(new TEQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeCours");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="codeAccesUniversel";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel!=null?codeAccesUniversel:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="motPasse";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse!=null?motPasse:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                return (ListeDeCours)getResult(ListeDeCours.class,__result,"listeCoursResult",__envelope);
            }
        },"http://etsmtl.ca/listeCours");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult<ListeDeCours>> listeCoursAsync(final String codeAccesUniversel, final String motPasse)
    {
        return executeAsync(new Functions.IFunc<ListeDeCours>() {
            public ListeDeCours Func() throws java.lang.Exception {
                return listeCours( codeAccesUniversel,motPasse);
            }
        });
    }
    
    public Boolean donneesAuthentificationValides(final String codeAccesUniversel,final String motPasse ) throws java.lang.Exception
    {
        return (Boolean)execute(new TEQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "donneesAuthentificationValides");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="codeAccesUniversel";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel!=null?codeAccesUniversel:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="motPasse";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse!=null?motPasse:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("donneesAuthentificationValidesResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://etsmtl.ca/donneesAuthentificationValides");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< Boolean>> donneesAuthentificationValidesAsync(final String codeAccesUniversel, final String motPasse)
    {
        return executeAsync(new Functions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return donneesAuthentificationValides( codeAccesUniversel,motPasse);
            }
        });
    }
    
    public ListeDeCours listeCoursIntervalleSessions(final String codeAccesUniversel, final String motPasse, final String SesDebut, final String SesFin ) throws java.lang.Exception
    {
        return (ListeDeCours)execute(new TEQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeCoursIntervalleSessions");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="codeAccesUniversel";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel!=null?codeAccesUniversel:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="motPasse";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse!=null?motPasse:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="SesDebut";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(SesDebut!=null?SesDebut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="SesFin";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(SesFin!=null?SesFin:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                return (ListeDeCours)getResult(ListeDeCours.class,__result,"listeCoursIntervalleSessionsResult",__envelope);
            }
        },"http://etsmtl.ca/listeCoursIntervalleSessions");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult<ListeDeCours>> listeCoursIntervalleSessionsAsync(final String codeAccesUniversel, final String motPasse, final String SesDebut, final String SesFin)
    {
        return executeAsync(new Functions.IFunc<ListeDeCours>() {
            public ListeDeCours Func() throws java.lang.Exception {
                return listeCoursIntervalleSessions( codeAccesUniversel,motPasse,SesDebut,SesFin);
            }
        });
    }
    
    public ListeDeSessions listeSessions(final String codeAccesUniversel, final String motPasse ) throws java.lang.Exception
    {
        return (ListeDeSessions)execute(new TEQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeSessions");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="codeAccesUniversel";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel!=null?codeAccesUniversel:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="motPasse";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse!=null?motPasse:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                return (ListeDeSessions)getResult(ListeDeSessions.class,__result,"listeSessionsResult",__envelope);
            }
        },"http://etsmtl.ca/listeSessions");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult<ListeDeSessions>> listeSessionsAsync(final String codeAccesUniversel, final String motPasse)
    {
        return executeAsync(new Functions.IFunc<ListeDeSessions>() {
            public ListeDeSessions Func() throws java.lang.Exception {
                return listeSessions( codeAccesUniversel,motPasse);
            }
        });
    }
    
    public listeDesProgrammes listeProgrammes(final String codeAccesUniversel, final String motPasse ) throws java.lang.Exception
    {
        return (listeDesProgrammes)execute(new TEQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "listeProgrammes");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="codeAccesUniversel";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(codeAccesUniversel!=null?codeAccesUniversel:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="motPasse";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(motPasse!=null?motPasse:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                return (listeDesProgrammes)getResult(listeDesProgrammes.class,__result,"listeProgrammesResult",__envelope);
            }
        },"http://etsmtl.ca/listeProgrammes");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult<listeDesProgrammes>> listeProgrammesAsync(final String codeAccesUniversel, final String motPasse)
    {
        return executeAsync(new Functions.IFunc<listeDesProgrammes>() {
            public listeDesProgrammes Func() throws java.lang.Exception {
                return listeProgrammes( codeAccesUniversel,motPasse);
            }
        });
    }
    
    public String listeCoequipiers(final String codeAccesUniversel,final String motPasse,final String pSigle,final String pGroupe,final String pSession,final String pNomElementEval ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> listeCoequipiersAsync(final String codeAccesUniversel, final String motPasse, final String pSigle, final String pGroupe, final String pSession, final String pNomElementEval)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return listeCoequipiers( codeAccesUniversel,motPasse,pSigle,pGroupe,pSession,pNomElementEval);
            }
        });
    }
    
    public String listeElementsEvaluation(final String codeAccesUniversel,final String motPasse,final String pSigle,final String pGroupe,final String pSession ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> listeElementsEvaluationAsync(final String codeAccesUniversel, final String motPasse, final String pSigle, final String pGroupe, final String pSession)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return listeElementsEvaluation( codeAccesUniversel,motPasse,pSigle,pGroupe,pSession);
            }
        });
    }
    
    public String listeHoraireEtProf(final String codeAccesUniversel,final String motPasse,final String pSession ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> listeHoraireEtProfAsync(final String codeAccesUniversel, final String motPasse, final String pSession)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return listeHoraireEtProf( codeAccesUniversel,motPasse,pSession);
            }
        });
    }
    
    public String listeHoraireExamensFin(final String codeAccesUniversel,final String motPasse,final String pSession ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> listeHoraireExamensFinAsync(final String codeAccesUniversel, final String motPasse, final String pSession)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return listeHoraireExamensFin( codeAccesUniversel,motPasse,pSession);
            }
        });
    }
    
    public String lireHoraire(final String pSession,final String prefixeSigleCours ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> lireHoraireAsync(final String pSession, final String prefixeSigleCours)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return lireHoraire( pSession,prefixeSigleCours);
            }
        });
    }
    
    public String lireJoursRemplaces(final String pSession ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> lireJoursRemplacesAsync(final String pSession)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return lireJoursRemplaces( pSession);
            }
        });
    }
    
    public String lireHoraireDesSeances(final String codeAccesUniversel,final String motPasse,final String pCoursGroupe,final String pSession,final String pDateDebut,final String pDateFin ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> lireHoraireDesSeancesAsync(final String codeAccesUniversel, final String motPasse, final String pCoursGroupe, final String pSession, final String pDateDebut, final String pDateFin)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return lireHoraireDesSeances( codeAccesUniversel,motPasse,pCoursGroupe,pSession,pDateDebut,pDateFin);
            }
        });
    }
    
    public String lireEvaluationCours(final String codeAccesUniversel,final String motPasse,final String pSession ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> lireEvaluationCoursAsync(final String codeAccesUniversel, final String motPasse, final String pSession)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return lireEvaluationCours( codeAccesUniversel,motPasse,pSession);
            }
        });
    }

    
    protected java.lang.Object execute(TEQIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        ExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, OperationResult< T>>  executeAsync(final Functions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, OperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected OperationResult< T> doInBackground(Void... params) {
                OperationResult< T> result = new OperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(OperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,ExtendedSoapSerializationEnvelope envelope)
    {

        return new java.lang.Exception(fault.faultstring);
    }
}


